name: praticeing github actions

on:
  push:
    branches: [test]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install dependencies
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin 
        # as my password contain some spical character i am using this
        # u can use docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-example .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-example:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/springboot-example:latest
      - name: Delete old container
        run: sudo docker rm -f springboot-example-container
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name springboot-example-container ${{ secrets.DOCKER_USERNAME }}/springboot-example
        